/** @format */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rahul Mallik - Portfolio",
  description: "Generated by Rahul Mallik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} scroll-smooth antialiased`}
        style={{
          fontFamily: "'Gilroy-Regular-Regular', Helvetica, sans-serif",
        }}
      >
        <div className="bg-[#1b1b1b] w-full flex mx-auto min-h-dvw">
          <div className="mx-auto w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
