/** @format */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/CommonComponents/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          fontFamily: "'Gilroy-Regular-Regular', Helvetica, sans-serif",
        }}
      >
        <div className="bg-[#1b1b1b] w-full flex mx-auto min-h-dvw">
          <div className=" mx-auto w-full ">
            <NavBar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
